### ISSUE TITLE
Set hostname and trace analytics via JSON config

### ISSUE THREAD

**Issue by cgilmour** [DataDog/dd-opentracing-cpp#110]
This library is used by ingress-nginx, which uses nginx-opentracing to load the plugin, and ingress-nginx generates a JSON file to configure the tracer.

Most settings are supported via JSON, but some newer ones are not.
The reason during development was because they affect a different path in the codebase - its internal `WritingSpanBuffer` - and the target during development didn't load config via JSON.

The inconsistency has affected a developer that wanted to add these new features to ingress-nginx as options the user can set, because it couldn't add them to the generated JSON to set them.
While there are other ways to make it work, it's hard to explain to users and is a bit hacky.

Related:
- Issue: https://github.com/kubernetes/ingress-nginx/issues/4372
- PR: https://github.com/kubernetes/ingress-nginx/pull/4373

**Comment by alanjcastonguay** [comment]
@cgilmour what happened with this? The 1.1.0 milestone looks weird.

**Comment by cgilmour** [comment]
Sorry @alanjcastonguay this didn't get implemented yet, and I also didn't update about it in comments.

I'll aim to get it completed by the end of this week.

**Comment by cgilmour** [comment]
Just to give an update: I've been working on this today, and it'll be part of a bundle of fixes we intend to release this week.
