### ISSUE TITLE
Event not getting reflected on Datadog dashboard

### ISSUE THREAD

**Issue by preetigaur** [DataDog/dd-opentracing-cpp#111]
Hi 

I tried out the dynamic loading example given in `dd-opentracing-cpp/examples/cpp-tracing/dynamic-loading/tracer_example.cpp`

Events are not getting reflected on the datadog dashboard.

Following are datadog-agent logs

<img width="1276" alt="Error" src="https://user-images.githubusercontent.com/7146976/64124385-8af35e00-cdc4-11e9-9d03-41bdc3225874.png">

Is there anything I am missing out?

**Comment by cgilmour** [comment]
Hi @preetigaur, it looks like the example is crashing.

```sh-session
$ docker-compose logs dd-opentracing-cpp-example
Attaching to dynamic-loading_dd-opentracing-cpp-example_1
dd-opentracing-cpp-example_1  | Tracer example
dd-opentracing-cpp-example_1  | terminate called after throwing an instance of 'opentracing::v2::util::bad_variant_access'
dd-opentracing-cpp-example_1  |   what():  in get<T>()
dd-opentracing-cpp-example_1  | ./run_things.sh: line 6:     8 Aborted                 (core dumped) ./tracer_example
dd-opentracing-cpp-example_1  | Tracer example with std::string tag
dd-opentracing-cpp-example_1  | terminate called after throwing an instance of 'opentracing::v2::util::bad_variant_access'
dd-opentracing-cpp-example_1  |   what():  in get<T>()
dd-opentracing-cpp-example_1  | Tracer example with const char*
dd-opentracing-cpp-example_1  | ./run_things.sh: line 9:    10 Aborted                 (core dumped) ./tracer_example_string
```

I'll see what can be done to fix it. Thanks for posting the issue.

**Comment by cgilmour** [comment]
Oops, that error I mentioned is coming from some local changes.
Running with a fresh checkout and `docker-compose build`, it runs as expected and finishes successfully.

<img width="1122" alt="Screen Shot 2019-09-03 at 09 36 21" src="https://user-images.githubusercontent.com/892558/64133994-78ae0a00-ce2e-11e9-93eb-0f29629fb687.png">

Do you see any messages at all from the example container? Or any errors reported by the agent container?
- `docker-compose logs dd-opentracing-cpp-example`
- `docker-compose logs dd-agent | grep ERROR`

**Comment by preetigaur** [comment]
I got it running. Thanks
