### ISSUE TITLE
Can't build the extension with opentracing-cpp v1.6.0

### ISSUE THREAD

**Issue by sanglt** [DataDog/dd-opentracing-cpp#115]
We have a script to get latest stable version and build the image every week. It not working anymore because the release from dd-opentracing-cpp only working with opentracing-cpp v1.6.0

Did we have plan to support this version?

**Comment by cgilmour** [comment]
Some work has been done on a [branch](https://github.com/DataDog/dd-opentracing-cpp/tree/cgilmour/opentracing-1.6.0) to support 1.6.0, but we don't have a plan for merging it yet.

I'll need to coordinate with other projects that either consume opentracing-cpp or implement tracers for it.

**Comment by tobiasstadler** [comment]
@cgilmour Are there any plans to support v1.6.0?

**Comment by cgilmour** [comment]
@tobiasstadler the two main projects that use opentracing-cpp (nginx-opentracing and envoy) have stuck with v1.5.1, so this project did as well. The v1.6.0 release isn't backward-compatible due to ABI changes, so it wasn't possible to update independently of those projects, or other tracers (eg: lightstep).

Is the interest due to specific features in that version or just desiring to work with the latest versions of things?
The branch made on this project to support v1.6.0 hasn't been kept updated due to apparent lack of interest.

**Comment by tobiasstadler** [comment]
Actually I would like to use the latest jaeger client with nginx-opentracing. As the jaeger-client uses v1.6.0, nginx-opentracing and its plug-ins need to be updated as well.

**Comment by timmysilv** [comment]
Bumping this thread - is there any plan to merge that branch soon? Projects using this client are still blocked from upgrading opentracing-cpp to 1.6.0 because of this issue.

**Comment by cgilmour** [comment]
Yup, within a week or so. It'll be included in the next release (v1.3.0).

**Comment by miry** [comment]
I see that the branch CI is failed because it relies on prebuilt module in nginx-opentracing.
Here is my PR to build nginx-opentracing with Opentracing 1.6.0

https://github.com/opentracing-contrib/nginx-opentracing/pull/155/files

**Comment by cgilmour** [comment]
Thanks @miry! I'd seen the PR and was trying to decide whether to merge even with the failing E2E test or update the test to use your 1.6.0 branch.

Even though it's extra work, updating the test will give us the reassurance that the changes are working properly together, or uncover if additional changes are needed before you and I can merge these PRs.

**Comment by miry** [comment]
@cgilmour Good plan. I have added your branch and nginx-opentracing build was finished with success.

**Comment by timmysilv** [comment]
🍾 
Can the latest commit be tagged and released as well?

**Comment by cgilmour** [comment]
Hi @timmysilv, this has been released now.
If you're planning another update to ingress-nginx, can it use this release tag and a newer version of nginx-opentracing? I'm OK doing that as well, but don't want to conflict with your efforts.

**Comment by timmysilv** [comment]
I just updated it to a commit hash and nginx-opentracing 0.11.0. Once a separate issue in the jaeger client is resolved, I'll update it again with all the proper versions. Thank you!
