### ISSUE TITLE
no opentracing context value found for span context key x_datadog_sampling_priority for request xxxxxxx

### ISSUE THREAD

**Issue by alessandro-c** [DataDog/dd-opentracing-cpp#124]
Hi, I've tried to enable distributed tracing but since I did nginx started popping out the error

`no opentracing context value found for span context key x_datadog_sampling_priority for request {request id}`

On top of that, the traces from our services originated from the reverse proxied requests by nginx are no longer logged in the APM.

I tried disabling the `dd.priority.sampling` from dd-config.json but still the same issue.

Here's the (relevant) nginx.conf I'm using : 

```nginx
load_module modules/ngx_http_opentracing_module.so;

http {

    opentracing on;
    opentracing_tag http_user_agent $http_user_agent;
    opentracing_trace_locations off;
    opentracing_load_tracer /usr/local/lib/libdd_opentracing_plugin.so /etc/nginx/tracers/dd-config.json;

    server {

        location ~ /service {
           opentracing_operation_name "$request_method $uri";
           opentracing_tag "http.query_params" $args;
           opentracing_tag "resource.name" "/$version-$service";
           
           # propagate the active span context upstream, so that the trace can be
           # continued by the backend.
           # See http://opentracing.io/documentation/pages/api/cross-process-tracing.html
           opentracing_propagate_context;
        }
    }
}
```

And finally the dd-config.json : 

```json
{
  "service": "nginx",
  "dd.priority.sampling": false,
  "environment": "production",
  "agent_host": "dd-agent",
  "agent_port": 8126
}
```

Could you please help/point me in the right direction?

Thank you

**Comment by cgilmour** [comment]
Can you try again with `dd.priority.sampling` set to `true` and confirm you're seeing the error?

Which versions are you using for each of these?
- nginx
- nginx-opentracing
- dd-opentracing-cpp

> traces from our services originated from the reverse proxied requests by nginx are no longer logged in the APM.
That is probably related to the error you reported.

**Comment by alessandro-c** [comment]
Found the problem, I was using `opentracing/nginx-opentracing:0.9.0` (latest at the moment) which is still using an old version of  dd-opentracing (https://github.com/opentracing-contrib/nginx-opentracing/blob/v0.9.0/Dockerfile#L10)

Upgrading to https://github.com/opentracing-contrib/nginx-opentracing/commit/894927f8eb90daea4c2ad4c251b6151e93ac7c47#diff-3254677a7917c6c01f55212f86c57fbf fixed it.
