### ISSUE TITLE
std::__1::system_error: mutex lock failed

### ISSUE THREAD

**Issue by preetigaur** [DataDog/dd-opentracing-cpp#129]
Hi 

I am trying to create child span :
 auto tracer = datadog::opentracing::makeTracer(tracer_options);  
 auto span = tracer->StartSpan("name");  
 auto childSpan = tracer->StartSpan("name", {opentracing::ChildOf(&span->context())});
  
Application crashes  when childSpan is created with the following error :
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument

**Comment by cgilmour** [comment]
Hi @preetigaur thanks for reporting this.
I'm unable to reproduce this in my current environment.
Can you provide some more details about yours?

I'm you're building dd-opentracing-cpp from master and running macos, because the `dylib` extension.

Can you provide details about the compiler version, how you install the `opentracing` dependency, and also try running your program in a debugger (eg: `lldb`) to capture a backtrace.

Thanks!

**Comment by byungminkim** [comment]
I couldn't also create child-span and application crashed.
If I don't make 'span b' span below code then it's okay.

datadog::opentracing::TracerOptions tracer_options{tracing_agent_host, 8126, tracingSystemName};
auto tracer = datadog::opentracing::makeTracer(tracer_options);

{
auto span_a = tracer->StartSpan("A");
auto span_b = tracer->StartSpan("B", {opentracing::ChildOf(&span_a->context())});
}


Here is  gdb output.
#0  0x00007f3970168d00 in pthread_mutex_lock () from /lib64/libpthread.so.0
#1  0x00007f39708fc77f in __gthread_mutex_lock (__mutex=0x8) at /opt/rh/devtoolset-7/root/usr/include/c++/7/x86_64-redhat-linux/bits/gthr-default.h:748
#2  lock (this=0x8) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/std_mutex.h:103
#3  lock_guard (__m=..., this=<synthetic pointer>) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/std_mutex.h:162
Python Exception <class 'gdb.error'> There is no member or method named _M_head_impl.:
#4  datadog::opentracing::Span::setSamplingPriority (this=0x0, user_priority=) at /source/dd-opentracing-cpp/src/span.cpp:389

I'm using libdd_opentracing.so(c04df98), libopentracing.so.1.6.0 with gcc-7.3.1 in CentOS 7.3 docker-container.

@cgilmour Could you please let me know a proper solution?

**Comment by dgoffredo** [comment]
CentOS 7 is not fully supported for our tracer, as far as I understand.

Here's my attempt at getting a minimal tracing example like yours to run under CentOS 7.9 using GCC 7: https://github.com/dgoffredo/centos7-devtoolset-7

Currently I'm having linkage issues.

If this is still causing you trouble, @preetigaur, and you are able to upgrade your system, you might try that. CentOS 8, for example, is known to work.
