### ISSUE TITLE
Use version 1.2.0 in envoy 

### ISSUE THREAD

**Issue by pawelkopka** [DataDog/dd-opentracing-cpp#153]
Is there a plan to update dd-opentracing-cpp version in enovy to 1.2.0?

**Comment by cgilmour** [comment]
Hi @pawelkopka we did plan to, but wanted to land a couple of additional features in a 1.2.1 release before updating envoy.
Those got de-prioritized and I never got back to doing the envoy update/retest/PR.
I'll try to get it done in the next week or two.

**Comment by cgilmour** [comment]
This took longer than hoped to complete, but envoyproxy/envoy#14837 was submitted and merged a little while ago.

**Comment by dgoffredo** [comment]
Still at version 1.2.1: https://github.com/envoyproxy/envoy/blob/4aab7faa910e85c0832345c7113ff41859ba607d/bazel/repository_locations.bzl#L364
Closing this.
