### ISSUE TITLE
Missing release v1.2.1?

### ISSUE THREAD

**Issue by littldr** [DataDog/dd-opentracing-cpp#157]
Hi!

I stumbled about an issue which is fixed in 2559d2813a8ee14ba18bd7d67909656a3af94642. But this change was not released yet (even though the version was bumped to `v1.2.1` in this commit).

Any chance to get an official release of `v1.2.1` in the next time? :)

**Comment by cgilmour** [comment]
Hi! This has been released now.

Sorry for the confusion but the version-bump happens on the first PR after each release. There's a CI check to ensure we (mainly me) don't forget to keep it updated.

**Comment by dgoffredo** [comment]
Now I'll have to remember, too.
