### ISSUE TITLE
worker process exited on signal 9

### ISSUE THREAD

**Issue by rvangundy** [DataDog/dd-opentracing-cpp#161]
I've just installed opentracing in to our nginx Docker image. For the first time, I started to see `worker process 11 exited on signal 9` and similar alerts in our log stream. We did not see these prior to installing dd-opentracing. I understand a signal 9 is often related to an OOMKill, but I am not seeing an associated OOMKill event from our scheduler (kubernetes), so it appears to be internal to the process. Also we are not seeing memory overallocation or CPU spikes on the container.

Is this something you've encountered?

**Comment by cgilmour** [comment]
I haven't encountered that before, sorry!
A signal 9 is a `SIGKILL`, that basically tells the kernel to "stop this process immediately and clean it up". It's a sign that the supervisor of the process is rather upset. Luckily it's easy to grep for, so I'm pretty sure it's coming from nginx's supervising and [handling of worker processes](https://github.com/nginx/nginx/blob/1e92a0a4cef98902aed35d7b402a6a402951aba4/src/os/unix/ngx_process_cycle.c#L193-L198).

At a quick read, it seems to try and stop a worker process "nicely" using SIGTERM, but if it's still alive after 1.0 seconds, a SIGKILL is used. I strongly suspect this is the source of the alert.

This bit is a guess: the tracer is taking more than 1.0 seconds to finish sending its remaining traces to the datadog agent. Nginx is impatient, sends the SIGKILL and reports that fact.

**Comment by dgoffredo** [comment]
Have you seen this issue much since, rvangundy?

If so, we could investigate Caleb's suspicion by throttling the tracer's communication with the agent and see if we can get nginx to timeout on shutdown.

If not, then we might be able to close this issue as a fleeting mystery.
