### ISSUE TITLE
Unhandled exception when running "compiled-in" example code on Windows

### ISSUE THREAD

**Issue by brotherpboon** [DataDog/dd-opentracing-cpp#170]
Hi.  I'm trying to run the compiled-in example on a local Windows machine.  I am getting an unhandled exception on line 91 file tracer_options.cpp (see attached image and code below).  Please advise.

Here is my code:
```
#include <datadog/opentracing.h>
#include <datadog/tags.h>
#include <iostream>
#include <string>

int main()
{
	datadog::opentracing::TracerOptions tracer_options{ "localhost", 8126, "compiled-in example" };
	auto tracer = datadog::opentracing::makeTracer(tracer_options);  <=== this line leads to exception

	// Create some spans.
	{
		auto span_a = tracer->StartSpan("A");
		span_a->SetTag(datadog::tags::environment, "production");
		span_a->SetTag("tag", 123);
		auto span_b = tracer->StartSpan("B", { opentracing::ChildOf(&span_a->context()) });
		span_b->SetTag("tag", "value");
	}

	tracer->Close();
    std::cout << "Hello World!\n";
}
```

=====================================================================

![exception](https://user-images.githubusercontent.com/55099558/113423829-cab16b80-9394-11eb-8207-a98066a0ba50.JPG)

```
ot::expected<TracerOptions, const char *> applyTracerOptionsFromEnvironment(
    const TracerOptions &input) {
  TracerOptions opts = input;   <===== this line causes the exception

  auto environment = std::getenv("DD_ENV");
  if (environment != nullptr && std::strlen(environment) > 0) {
    opts.environment = environment;
  }

  auto service = std::getenv("DD_SERVICE");
  if (service != nullptr && std::strlen(service) > 0) {
    opts.service = service;
  }
```

**Comment by brotherpboon** [comment]
This runtime exception only occurs in debug build.  I am able to run release without any issue.

**Comment by cgilmour** [comment]
Thanks for reporting this @brotherpboon, and good to know it works as-expected for release builds.
It took a few attempts and some user-error, but your clue about debug builds has helped me to reproduce this.

Not yet sure what I can do to fix it. The code it is failing on is fairly ordinary, no hidden magic to it.

**Comment by brotherpboon** [comment]
I was able to get it to run under debug code if I rebuild and set the configuration to Debug instead of RelWithDebInfo

`cmake --build . -- -p:Configuration=Debug`

Then I had to change the dependencies' names accordingly under Project properties->Linker->Input.

For example:

libcurl.lib to libcurl-d.lib
zlib.lib to zlibd.lib

I am now able to send traces to DD running under both debug and release configurations.

**Comment by cgilmour** [comment]
Thanks for the update @brotherpboon and confirming the issue was from mixing debug and release builds for libraries and an approach to avoid it.

**Comment by dgoffredo** [comment]
I've created https://github.com/DataDog/dd-opentracing-cpp/pull/198 to make note of this potential issue in our Windows build instructions.
