### ISSUE TITLE
Support for DD_TRACE_RATE_LIMIT

### ISSUE THREAD

**Issue by ejholmes** [DataDog/dd-opentracing-cpp#173]
Most of the standard APM clients (Ruby/Go) have support for configuring the client level rate limiter, via a `DD_TRACE_RATE_LIMIT` environment variable:

* Ruby: https://github.com/DataDog/dd-trace-rb/blob/d92ecc3568367cda6e017ba4556ab9e042e45f7d/lib/ddtrace/configuration/settings.rb#L183-L186
* Go: https://github.com/DataDog/dd-trace-go/blob/3ed2a2784fd7adb414f2f47dbb6b6a1d301cdf8c/ddtrace/tracer/sampler.go#L262-L280

By the looks of it, the rate limiter here is hard coded, and can't be configured via an environment variable: https://github.com/DataDog/dd-opentracing-cpp/blob/2559d2813a8ee14ba18bd7d67909656a3af94642/src/sample.cpp#L68

**Comment by cgilmour** [comment]
Yeah, that's correct. I'll add support for this.

**Comment by dgoffredo** [comment]
This is released as of [v1.3.2](https://github.com/DataDog/dd-opentracing-cpp/releases/tag/v1.3.2).
