### ISSUE TITLE
License missing copyright owner

### ISSUE THREAD

**Issue by ssgelm** [DataDog/dd-opentracing-cpp#192]
The Apache 2.0 license file at https://github.com/DataDog/dd-opentracing-cpp/blob/master/LICENSE#L190 is missing the name of the copyright owner and instead just says:
```
   Copyright [yyyy] [name of copyright owner]
```
Can you please update this with the name of the copyright owner (I'm assuming it's DataDog)

**Comment by cgilmour** [comment]
Thanks for reporting this! Your assumption is correct.
Before fixing it, I'll check internally to see whether it should be dual-license (Apache 2.0 + BSD 3) to match our other tracers.
