### ISSUE TITLE
Cross compilation in Alpine fails

### ISSUE THREAD

**Issue by lucacome** [DataDog/dd-opentracing-cpp#203]
I'm trying to cross-compile in Alpine and I get this error:
```
#25 112.4 /dd-opentracing-cpp/include/datadog/opentracing.h:19:10: fatal error: 'opentracing/tracer.h' file not found
#25 112.4 #include <opentracing/tracer.h>
#25 112.4          ^~~~~~~~~~~~~~~~~~~~~~
#25 113.4 1 error generated.
```
but everything works fine when I build natively. 

Any ideas on how to fix this?

**Comment by cgilmour** [comment]
Looks like the opentracing headers aren't installed or the compiler doesn't know where to find them.
What build environment are you using?

**Comment by lucacome** [comment]
This is the Dockerfile I'm working on https://github.com/opentracing-contrib/nginx-opentracing/blob/feat/add-alpine-image/Dockerfile#L173:L189

Currently works for Debian, and for Alpine for amd64 (i.e. not cross-compiling). I can't figure out what could cause this problem.
Just for reference, these are the cross-compilation helpers https://github.com/tonistiigi/xx

**Comment by dgoffredo** [comment]
I'm still learning cmake, but I see this

https://github.com/opentracing-contrib/nginx-opentracing/blob/4869b5b843eeb2efcb3b7b424a10279a936a8f10/Dockerfile#L94-L112

copying the opentracing shared object if `"$(xx-info sysroot)" != "/"`, but it doesn't move the headers. Maybe that's fine, but I kept it in mind.

Then when building our code you use `CMAKE_PREFIX_PATH`: https://github.com/opentracing-contrib/nginx-opentracing/blob/4869b5b843eeb2efcb3b7b424a10279a936a8f10/Dockerfile#L196

In our cmake config, we have https://github.com/DataDog/dd-opentracing-cpp/blob/0cb27e442c1c3d8d8302547a429a8dfa4a0cde28/CMakeLists.txt#L34 and then https://github.com/DataDog/dd-opentracing-cpp/blob/0cb27e442c1c3d8d8302547a429a8dfa4a0cde28/CMakeLists.txt#L38.

The `set(CMAKE_LIBRARY_PATH deps/lib)` allows us to build using build-tree-local-installed versions of our dependencies (see https://github.com/DataDog/dd-opentracing-cpp/blob/master/scripts/install_dependencies.sh), but if the dependencies are installed "on the system," that is supposed to work too.

What are the interactions among `CMAKE_PREFIX_PATH`, `CMAKE_LIBRARY_PATH`, and the system directory structure as seen by the compiler?

I don't know, but maybe the answer is somewhere in there. Perhaps `$(xx-info sysroot)` is to blame (or, if it's `"/"`, then it probably isn't to blame).
