### ISSUE TITLE
Any plans to integrate with open-telemetry/opentelemetry-cpp-contrib?

### ISSUE THREAD

**Issue by johnjameswhitman** [DataDog/dd-opentracing-cpp#220]
We're in the process of setting DataDog up with nginx, and are planning to follow the recommendations in the [DD docs](https://docs.datadoghq.com/tracing/setup_overview/proxy_setup/?tab=nginx) to use the opentracing-contrib/nginx-opentracing repo, and want to make sure this'll be a supported method for at least the next year.

On the [opentracing site](https://opentracing.io/) I noticed they've started pointing folks over to the open-telemetry project (aka _otel_), which has a corresponding plugin for Nginx here: https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/nginx.

I couldn't find any datadog references in the opentelemetry-cpp-contrib repo, but also noticed some DD docs that hint the agent has a beta-feature to [receive OTLP traces and metrics](https://docs.datadoghq.com/tracing/setup_overview/open_standards/#otlp-ingest-in-datadog-agent). At some point will opentelemetry-cpp-contrib &rarr; DD agent become the supported technique to trace Nginx?

**Comment by dgoffredo** [comment]
So long as the Datadog Agent can receive OTLP traces, you will always be able to use whatever OpenTelemetry integrations exist for nginx.

Right now, as you point out, we primarily support use of OpenTracing's nginx-opentracing in conjunction with our plugin.

In the near future we will also support a similar Datadog-specific nginx module.  We will continue to support the documented nginx-opentracing setup, though migrating from the latter to the former will be trivial.  More on that coming soon.

I think your best bet for now is to use nginx-opentracing.
