### ISSUE TITLE
zlib 1.2.11 install dependency is broken

### ISSUE THREAD

**Issue by DamianTran** [DataDog/dd-opentracing-cpp#222]
The install dependency link for zlib ([https://zlib.net/zlib-1.2.11.tar.gz](https://zlib.net/zlib-1.2.11.tar.gz)) is now broken, and returns a 404.  This is likely because zlib is enforcing an update to their newest version [1.2.12](https://zlib.net/zlib-1.2.12.tar.gz).  The result is a 404 error when trying to install from the [C++ opentracing install instructions](https://docs.datadoghq.com/tracing/setup_overview/setup/cpp/?tab=containers)

After running

```
# Download and install the correct version of opentracing-cpp, & other deps.
../scripts/install_dependencies.sh
```

The error encountered:

```
--2022-04-02 01:14:47--  https://zlib.net/zlib-1.2.11.tar.gz
Resolving zlib.net (zlib.net)... 85.187.148.2
Connecting to zlib.net (zlib.net)|85.187.148.2|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-04-02 01:14:47 ERROR 404: Not Found.
```

The notice from zlib.net:

```
Version 1.2.12 has these key improvements over 1.2.11:

Fix a deflate bug when using the Z_FIXED strategy that can result in out-of-bound accesses.
Fix a deflate bug when the window is full in deflate_stored().
Speed up CRC-32 computations by a factor of 1.5 to 3.
Use the hardware CRC-32 instruction on ARMv8 processors.
Speed up crc32_combine() with powers of x tables.
Add crc32_combine_gen() and crc32_combine_op() for fast combines.

Due to the bug fixes, any installations of 1.2.11 should be replaced with 1.2.12.
```

Recommend altering line 12 of `scripts/install_dependencies.sh` to the updated 1.2.12 version to fix this

**Comment by cgilmour** [comment]
Thanks for reporting this and providing so much detail!
I've made the suggested change in #223
