### ISSUE TITLE
Errors when `x-datadog-sampling-priority` header is present but `x-datadog-tags` is not

### ISSUE THREAD

**Issue by hiddewie** [DataDog/dd-opentracing-cpp#241]
Nginx version: 1.23.1
Datadog opentracing version: 1.3.4 (issue is also present in 1.3.3, but not in 1.3.2)
Nginx opentracing version: 0.26.0

Nginx server config
```
server {
  listen 9000 default_server;

  opentracing on;
  opentracing_trace_locations off;
  opentracing_tag http_user_agent $http_user_agent;
  opentracing_operation_name nginx.request;
  opentracing_propagate_context;

  location / {
    # proxy ...
  }
}
```

When the request contains the headers 
```
x-datadog-parent-id: 628590525536830299
x-datadog-sampling-priority: 0
x-datadog-trace-id: 8761565436669190370
```
the following error is emitted
```
2022/09/06 08:33:46 [error] 102#102: *17 no opentracing context value found for span context key x_datadog_tags for request 00007FF9B25D2450, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:9000"
```

If I add the header 
```
x-datadog-tags: a=b
```
the nginx error is not emitted anymore.

I suspect the pull request https://github.com/DataDog/dd-opentracing-cpp/pull/230

**Comment by sanglt** [comment]
Yes we have the same issue and need to rollback to v1.3.2

**Comment by dgoffredo** [comment]
Thanks for reporting this.

I probably need a branch like this for `x-datadog-tags`: <https://github.com/DataDog/dd-opentracing-cpp/blob/9b9248f869fdfb8afc236499138d06a552451113/src/span_context.cpp#L391-L397>.  `nginx-opentracing` needs to know in advance which HTTP headers we might add to the upstream request.  It does this by pretending to serialize some trace context, and then inspects the headers written. The tracer is expected to detect this pretend serialization and write all tags that it ever might.  The issue probably is that I didn't add `x-datadog-tags` there.

Our nginx integration test didn't catch this.  I'll play with it and propose a fix.

**Comment by dgoffredo** [comment]
https://github.com/DataDog/dd-opentracing-cpp/pull/242

**Comment by hiddewie** [comment]
Thanks for looking into this quickly!

**Comment by dgoffredo** [comment]
https://github.com/DataDog/dd-opentracing-cpp/releases/tag/v1.3.5
