### ISSUE TITLE
error log "Requested trace_id not found in SpanBuffer::serializeTraceTags" with datadog config for nginx

### ISSUE THREAD

**Issue by KIWOKIM** [DataDog/dd-opentracing-cpp#256]
Hello, 

I setup datadog tracing and it works. 
But, if I use subrequest in nginx then the below logs appeared. 

Is there any way to resolve that error logs? 

It seems that the trace_id is used in multiple functions in same file (span_buffer.cpp ) but, I see below error logs only. 
So, it looks other functions are working. 

--------------------------------------------------
2023/03/09 02:05:21 [error] 24#24: datadog: [trace_id: 1540204378199792628] Requested trace_id not found in SpanBuffer::serializeTraceTags
-------------------------------------------------

**Background :** 
my nginx sends the request to "/auth"  in one of the location block in nginx itself (subrequest) 
Then the /auth will proxy the request to actual auth server. 

And in the actual auth server, it also creates its own span as a child span of the span from nginx and update the trace with relevant tags.

**Comment by dgoffredo** [comment]
Hi, KIWOKIM.

Which version of which nginx module are you using, with which version of nginx, and on which system?
- e.g. "nginx-opentracing v0.28.0 with nginx 1.23.2 on Debian 11"
- or "nginx-datadog v0.5.3 with nginx 1.19.0 on Alpine 3.16"

Also, could you share a copy of your nginx configuration, perhaps with unrelated information redacted?

**Comment by KIWOKIM** [comment]
Hello @dgoffredo 
Thank you for handling this incident! 

Please refer to below information. 

1. Version : 
- Nginx : the image from Docker Hub nginx:1.22.1-alpine on alpine:3.16, 3.16.4
- Module : nginx-datadog v0.4.0

2. nginx.conf : 

===========================================

```
load_module modules/ngx_http_datadog_module.so;

worker_processes auto;

pid        /tmp/nginx.pid;

error_log  /dev/stderr warn;

events {
    worker_connections 8192;
}

http {
  default_type application/octet-stream;


  client_max_body_size 1m;
  client_body_buffer_size 1m;

  client_body_in_single_buffer on;


  log_format   log_main '$time_local, $pid, $remote_addr, $http_referer, $http_user_agent, $request_time, $upstream_response_time, $request_time, $request_length, $bytes_sent, $status, $request_method, $content_type, $host, $http_x_target_tmap_host, $server_port, $request_uri, $uri';

  access_log   /dev/stdout  log_main;

  client_body_temp_path /tmp/client_temp;
  proxy_temp_path       /tmp/proxy_temp_path;
  fastcgi_temp_path     /tmp/fastcgi_temp;
  uwsgi_temp_path       /tmp/uwsgi_temp;
  scgi_temp_path        /tmp/scgi_temp;

  ignore_invalid_headers on;
  underscores_in_headers on;

  datadog_enable;
  datadog_trace_locations off;

  server {

    listen 8080;

    access_log   /dev/stdout  log_main;

    server_tokens off;

    log_subrequest on;

    auth_delay 3s;

    location / {

      auth_request /auth;

      datadog_operation_name $http_x_target_host;

      access_log   /dev/stdout  log_main;
      
      limit_except GET POST {
        deny all;
      }

      proxy_pass https://$http_x_target_host$request_uri;

      proxy_ssl_protocols TLSv1.2 TLSv1.3;
      proxy_ssl_name $http_x_target_host;
      proxy_ssl_server_name on;
      proxy_ssl_verify on;
      proxy_ssl_trusted_certificate /etc/ssl/certs/public-ca.crt;
    }

    location /auth {

      internal;

      access_log   /dev/stdout  log_main;

      rewrite ^(.*)$ /valid?auth=$http_x_auth break; 

      proxy_method GET;
      proxy_pass_request_body off;
      proxy_pass_request_headers off;

      proxy_pass http://myauth;
    }
  }
}
```

**Comment by dgoffredo** [comment]
I'm playing around with this on a special branch of `nginx-datadog`: https://github.com/DataDog/nginx-datadog/blob/david.goffredo/trace-not-found-in-serializeTraceTags/example/services/nginx/nginx.conf

I reduced the amount of worker processes, removed HTTPS, toggled location tracing, etc.

I've got auth requests and upstream requests working, and I see the expected traces in the Datadog UI, but I have not yet seen the error message. Maybe it's a timing thing.

Is there anything you notice about the particular requests that result in the error message being printed? For example, maybe it's only when the auth service rejects the request (or something).

I'll play around with this a bit more, but currently I'm unable to reproduce the error message.

You can run the demo by following the instructions in the readme of the `example/` directory of the branch linked above.

Briefly,

shell1:
```console
$ cd example/
$ DD_API_KEY=your_api_key bin/run
[ ... ]
```

shell2:
```console
$ cd example/
$ bin/curl -H 'X-Target-Host: http' -H 'X-Response-Status: 201' -H 'X-Auth: foo' -H 'X-Datadog-Trace-Id: 123' -H 'X-Datadog-Parent-Id: 456' 'http://nginx'
WARN[0000] The "BASE_IMAGE" variable is not set. Defaulting to a blank string. 
{
  "service": "http",
  "headers": {
    "x-datadog-trace-id": "123",
    "x-datadog-parent-id": "6135376305329518080",
    "x-datadog-sampling-priority": "1",
    "x-datadog-tags": "_dd.p.dm=-0",
    "host": "http",
    "connection": "close",
    "user-agent": "curl/7.80.0",
    "accept": "*/*",
    "x-target-host": "http",
    "x-response-status": "201",
    "x-auth": "foo"
  }
}
```
Traces show up in the UI as `service:nginx-datadog-example`.

I've added the `X-Response-Status` request header to make the upstream return different HTTP response statuses. The auth service does not get forwarded this header, for some reason.

`X-Target-Host` is the host of the upstream, per your configuration. In this docker compose setup, `http` is a service that responds with a JSON representation of its request headers. `myauth` is another instance of the same service.

By playing with `X-Target-Host`, you can get different behavior:
- `X-Target-Host: http` is the "normal case," where the upstream is different from the auth service.
- `X-Target-Host: myauth` sets the upstream to be the same as the auth service, so you'll see it log two requests. Works.
- `X-Target-Host: nginx` is a routing loop that will generate a ton of logging before finally failing.
- `X-Target-Host: something-else` fails to resolve, because the specified `resolver` only knows about the names of the docker compose services.

Happy bug hunting!

**Comment by KIWOKIM** [comment]
@dgoffredo Thanks a lot for your information! 
I will test it soon and give you feedback!

**Comment by KIWOKIM** [comment]
@dgoffredo 

Hello. 
Here is some update and I would like to add logs.

Do you think that sending trace from my Auth service caused the below error logs in nginx module? 

- Sending trace from **Auth service**
2023/03/15 03:12:34 Datadog Tracer v1.48.0 DEBUG: Sending payload: size: 575 traces: 1
2023/03/15 03:12:34 Datadog Tracer v1.48.0 DEBUG: sent traces after 1 attempts

- Error from **Nginx**
_**2023/03/15 03:12:34 [error] 25#25: datadog: [trace_id: 1146651056954184957] Requested trace_id not found in SpanBuffer::serializeTraceTags**_

==================================================== 


1. **Auth service (written in Go with dd-trace-go.v1)** 

--> This is requested by nginx 
```
2023/03/15 01:53:08 Datadog Tracer v1.48.0 INFO: DATADOG TRACER CONFIGURATION {"date":"2023-03-15T01:53:08Z","os_name":"Linux (Unknown Distribution)","os_version":"unknown","version":"v1.48.0","lang":"Go","lang_version":"go1.19.3","env":"nonprod","service":"session-context-cache","agent_url":"http://10.224.0.5:8126/v0.4/traces","agent_error":"","debug":true,"analytics_enabled":true,"sample_rate":"NaN","sample_rate_limit":"disabled","sampling_rules":null,"sampling_rules_error":"","service_mappings":null,"tags":{"geo":"asia","region":"korea","runtime-id":"aaaaaaaa-1f6b-4e11-962f-1a19f6769761"},"runtime_metrics_enabled":true,"health_metrics_enabled":true,"profiler_code_hotspots_enabled":true,"profiler_endpoints_enabled":true,"dd_version":"v0.1.1","architecture":"amd64","global_service":"session-context-cache","lambda_mode":"false","appsec":false,"agent_features":{"DropP0s":true,"Stats":true,"StatsdPort":0}}

2023/03/15 03:12:33 Req Header :  {"Connection":["close"],"Content-Length":["812"],"X-Datadog-Parent-Id":["7777335962791349727"],"X-Datadog-Sampling-Priority":["2"],"X-Datadog-Trace-Id":["1146651056954184957"]}

2023/03/15 03:12:33 Datadog Tracer v1.48.0 DEBUG: Extracted span context: &tracer.spanContext{updated:false, trace:(*tracer.trace)(0xc00010c1c0), span:(*tracer.span)(nil), errors:0, traceID:0xfe9b90fa31494fd, spanID:0x6beea5da210c8ddf, mu:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, baggage:map[string]string(nil), hasBaggage:0x0, origin:""}

2023/03/15 03:12:33 Datadog Tracer v1.48.0 DEBUG: Started Span: dd.service=session-context-cache dd.env=nonprod dd.version=v0.1.1 dd.trace_id="1146651056954184957" dd.span_id="8934930852742097704", Operation: session.valid, Resource: session.valid, Tags: map[env:nonprod geo:amap language:go region:koreacentral runtime-id:a996604a-1f6b-4e11-962f-1a19f6769761 version:v0.1.1], map[_dd.top_level:1 _sampling_priority_v1:2 process_id:1]

2023/03/15 03:12:34 Datadog Tracer v1.48.0 DEBUG: Sending payload: size: 575 traces: 1

2023/03/15 03:12:34 Datadog Tracer v1.48.0 DEBUG: sent traces after 1 attempts
```

2. **Nginx** 

--> This is requested by client 
```
2023/03/15 03:12:33 [notice] 25#25: *926 "^(.*)$" matches "/auth", client: 10.244.0.90, server: , request: "POST /channel/search/find HTTP/1.1", subrequest: "/auth", host: "***.***.com"

2023/03/15 03:12:33 [notice] 25#25: *926 rewritten data: "/valid", args: "sessionId=d03300af-0236-4c89-94d0-0b55607e64a0", client: 10.244.0.90, server: , request: "POST /channel/search/find HTTP/1.1", subrequest: "/auth", host: "***.***.com"

2023/03/15 03:12:34 [error] 25#25: datadog: [trace_id: 1146651056954184957] Requested trace_id not found in SpanBuffer::serializeTraceTags

2023/03/15 03:12:34
{
	"time_local": "15/Mar/2023:03:12:34 +0000",
	"pid": "25",
	"remote_addr": "10.244.0.90",
	"status": "200",
	"request_method": "POST",
	"content_type": "application/json",
	"host": "***.***.com",
	"http_x_target_host": "aaa.bbb.co.kr:443",
	"server_port": "8080",
	"uri": "/valid",
	"args": "sessionId=d03300af-0236-4c89-94d0-0b55607e64a0",
	"datadog": {
		"http_x_datadog_trace_id": "1146651056954184957",
		"http_x_datadog_parent_id": "7251501704947672332",
		"datadog_trace_id": "1146651056954184957",
		"datadog_span_id": "7777335962791349727",
		"datadog_location": "/auth",
		"datadog_proxy_directive": "proxy_pass",
		"datadog_json": "{\"baggage\":{},\"parent_id\":\"7777335962791349727\",\"sampling_priority\":2,\"tags\":\"\",\"trace_id\":\"1146651056954184957\"}",
		"datadog_config_json": "{\"agent_url\":\"http://10.224.0.4:8126\",\"analytics_enabled\":false,\"analytics_sample_rate\":null,\"dd_version\":\"v0.1.119\",\"enabled\":true,\"env\":\"prod\",\"lang\":\"cpp\",\"lang_version\":\"201402\",\"report_hostname\":false,\"sampling_rules\":\"[]\",\"service\":\"nginx-proxy\",\"version\":\"v1.3.6\"}"
	},
	"js_request_subrequest_query_args": "{\"sessionId\":\"d03300af-0236-4c89-94d0-0b55607e64a0\"}",
	"js_request_subrequest_headers_json": "{\"x-datadog-trace-id\":\"1146651056954184957\",\"x-datadog-parent-id\":\"7251501704947672332\",\"x-datadog-sampling-priority\":\"2\",\"Host\":\"***.***.com\",\"X-Request-ID\":\"390d5e5fcaec38d4d0fecd1703f38ec8\",\"X-Real-IP\":\"xxx.xxx.3.201\",\"X-Forwarded-For\":\"xxx.xxx.3.201\",\"X-Forwarded-Host\":\"***.***.com\",\"X-Forwarded-Port\":\"443\",\"X-Forwarded-Proto\":\"https\",\"X-Forwarded-Scheme\":\"https\",\"X-Scheme\":\"https\",\"Content-Length\":\"812\",\"Accept\":\"application/json; charset=utf-8,application/json; charset=utf-8\",\"Requester\":\"CLIENT_SSL\",\"Network-Type\":\"WIFI\",\"x-target-host\":\"aaa.bbb.co.kr:443\",\"Accept-Encoding\":\"gzip\",\"X-SessionId\":\"d03300af-0236-4c89-94d0-0b55607e64a0\",\"Via\":\"1.1 localhost.localdomain:9081\",\"Content-Type\":\"application/json\",\"User-Agent\":\"PostmanRuntime/7.31.1\",\"Postman-Token\":\"8cd8d1de-c453-4815-af78-d72b195c3d99\"}",
	"js_request_subrequest_body_json": ""
}


2023/03/15 03:12:34
{
	"time_local": "15/Mar/2023:03:12:34 +0000",
	"pid": "25",
	"remote_addr": "10.244.0.90",
	"status": "200",
	"request_method": "POST",
	"content_type": "application/json",
	"host": "***.***.com",
	"http_x_target_host": "aaa.bbb.co.kr:443",
	"server_port": "8080",
	"uri": "/channel/search/find",
	"args": "",
	"datadog": {
		"http_x_datadog_trace_id": "1146651056954184957",
		"http_x_datadog_parent_id": "7251501704947672332",
		"datadog_trace_id": "1146651056954184957",
		"datadog_span_id": "2328981617914452652",
		"datadog_location": "/",
		"datadog_proxy_directive": "proxy_pass",
		"datadog_json": "{\"baggage\":{},\"parent_id\":\"2328981617914452652\",\"tags\":\"\",\"trace_id\":\"1146651056954184957\"}",
		"datadog_config_json": "{\"agent_url\":\"http://10.224.0.4:8126\",\"analytics_enabled\":false,\"analytics_sample_rate\":null,\"dd_version\":\"v0.1.119\",\"enabled\":true,\"env\":\"prod\",\"lang\":\"cpp\",\"lang_version\":\"201402\",\"report_hostname\":false,\"sampling_rules\":\"[]\",\"service\":\"nginx-proxy\",\"version\":\"v1.3.6\"}"
	},
	"js_request_default_query_args": "{}",
	"js_request_default_headers_json": "{\"x-datadog-trace-id\":\"1146651056954184957\",\"x-datadog-parent-id\":\"7251501704947672332\",\"x-datadog-sampling-priority\":\"2\",\"Host\":\"***.***.com\",\"X-Request-ID\":\"390d5e5fcaec38d4d0fecd1703f38ec8\",\"X-Real-IP\":\"xxx.xxx.3.201\",\"X-Forwarded-For\":\"xxx.xxx.3.201\",\"X-Forwarded-Host\":\"***.***.com\",\"X-Forwarded-Port\":\"443\",\"X-Forwarded-Proto\":\"https\",\"X-Forwarded-Scheme\":\"https\",\"X-Scheme\":\"https\",\"Content-Length\":\"812\",\"Accept\":\"application/json; charset=utf-8,application/json; charset=utf-8\",\"Requester\":\"CLIENT_SSL\",\"Network-Type\":\"WIFI\",\"x-target-host\":\"aaa.bbb.co.kr:443\",\"Accept-Encoding\":\"gzip\",\"X-SessionId\":\"d03300af-0236-4c89-94d0-0b55607e64a0\",\"Via\":\"1.1 localhost.localdomain:9081\",\"Content-Type\":\"application/json\",\"User-Agent\":\"PostmanRuntime/7.31.1\",\"Postman-Token\":\"8cd8d1de-c453-4815-af78-d72b195c3d99\"}",
	"js_request_default_body_json": "{\"name\":\"스타벅스 죽전\",\"reqSeq\":1,\"searchTypCd\":\"A\"}"
}

```

**Comment by dgoffredo** [comment]
> Q1. Is it possible to make the library verbose?

Yes, but it will not help here. You can try doing the following two things:

1. Increase nginx's error log verbosity, as you mentioned, by replacing the `error_log` directive with something like the following: `error_log stderr debug;`. nginx will produce a lot of output this way, but most of it will be unrelated to tracing.
2. Execute nginx in an environment having the variable `DD_TRACE_DEBUG=true`. This will cause the tracing library to log more output, but none of it looks relevant to the issue: <https://github.com/search?q=repo%3ADataDog%2Fdd-opentracing-cpp+%22-%3ETrace%28%22&type=code>. Also, be sure to add the following directive to your nginx configuration: `env DD_TRACE_DEBUG;` or `env DD_TRACE_DEBUG=true;`. Without this, nginx will not forward that environment variable to worker processes.

> Do you think that sending trace from my Auth service caused the below error logs in nginx module?

I don't know. I'm looking at the timestamps (which I know can't be trusted in general). The error in nginx was logged at "2023/03/15 03:12:34", while the auth service received the request apparently earlier at "2023/03/15 03:12:33".

If this is true, it means that nginx successfully made the request to the auth service and received the response, and _later_ failed to look up that trace when trying to inject context ("serializeTraceTags") to the upstream service.

So, in your setup, nginx creates a trace, propagates it to the auth service, gets the go-ahead from the auth response, and then tries to propagate the authenticated request to the upstream service, but at that point the trace ID is not registered in the tracer anymore.

I don't know how this can happen, but there was a similar bug in our tracer in the past that had to do with one trace "passing through" the proxy twice, e.g. a routing loop. That doesn't seem to be what's happening here, though.

**Comment by KIWOKIM** [comment]
Hello @dgoffredo 

I recently upgraded both nginx image and datadog nginx module as below. 
And I can confirm that this issue was resolved. 

- Nginx : the image from Docker Hub nginx:1.24.0-alpine
- Module : nginx-datadog v1.0.0

**Comment by dgoffredo** [comment]
That's great to hear!
