### ISSUE TITLE
DD_TRACE_SAMPLE_RATE not reflected in init logs

### ISSUE THREAD

**Issue by ahawkins** [DataDog/dd-opentracing-cpp#258]
I was working on configuring an `nginx` deployment to use sampling. I added `env DD_TRACE_SAMPLE_RATE` and set the environment variable to `0.1`. I restarted the deployment and checked the logs. Note that output should display `"sampling_rules": [{ "sample_rate": 0.1 }]` but just shows `[]`. The full log is below.

```
info: DATADOG TRACER CONFIGURATION - {"agent_url":"http://10.21.32.183:8126","analytics_enabled":false,"analytics_sample_rate":null,"date":"2023-04-21T23:39:52+0000","enabled":true,"env":"prod","lang":"cpp","lang_version":"201402","operation_name_override":"nginx.handle","report_hostname":false,"sampling_rules":"[]","service":"nginx","version":"v1.3.6"}
```

However, setting the `DD_TRACE_SAMPLE_RATE` is working. I can tell my tracking my ingested bytes metric in Datadog.

It seems reasonable to expect that sample rules set by `DD_TRACE_SAMPLE_RATE` should appear in the logs. The current behavior is confusing.

**Comment by dgoffredo** [comment]
Thanks for reporting this.

The sampling rule implied by `DD_TRACE_SAMPLE_RATE` is added to the rules after the configuration is processed. I wonder if even the environment variable `DD_TRACE_SAMPLING_RULES` would affect the displayed value for `"sampling_rules"`...

The new tracing library, https://github.com/DataDog/dd-trace-cpp, shows the final configured state of the tracer when printing this banner. Work is ongoing to move the nginx module, [TODO](https://github.com/DataDog/nginx-datadog), to the new library.

We might patch this library to sort out this issue, but probably not.

**Comment by ahawkins** [comment]
@dgoffredo thanks for explaining. I'll close this issue then.
