### ISSUE TITLE
is there a way to make this module FIPS compliant?

### ISSUE THREAD

**Issue by balusarakesh** [DataDog/dd-opentracing-cpp#259]
Hi,

We want to use this module to enable tracing for our nginx server in govcloud, is there a way to make/build this module FIPS compliant?

OR

if possible, is there a way to build the alternative module [nginx-datadog](https://github.com/DataDog/nginx-datadog) FIPS compliant?

 - Thank you

**Comment by balusarakesh** [comment]
OR if possible, is there a way to build the alternative module [nginx-datadog](https://github.com/DataDog/nginx-datadog) FIPS compliant?

**Comment by dgoffredo** [comment]
Hi @balusarakesh,

I don't know what the compliance verification process is for FIPS, but I'm fairly confident that `dd-opentracing-cpp` has not been evaluated. `nginx-datadog` definitely has not been evaluated.

Are you familiar with the process that an open source software project must go through to be used within govcloud? If so, I can reach out internally within my organization to see whether beginning the process would be worthwhile.

**Comment by balusarakesh** [comment]
gotcha, I'll work with datadog customer support on this.

 - Thank you
