### ISSUE TITLE
Support OpenTelemetry W3C headers "tracecontext"

### ISSUE THREAD

**Issue by David-Wobrock** [DataDog/dd-opentracing-cpp#261]
Hello 👋 

Is there any plan to support the `tracecontext` W3C headers that are used for OpenTelemetry?
If yes, is there an ETA on it? :)
If not, would you accept contributions adding support for it?

I think other Datadog tracing libs are supporting it already (at least the Python, Go and JS ones).

Thanks a lot! 💪

**Comment by dgoffredo** [comment]
Hi David,

Our new tracing library, [dd-trace-cpp][1], already supports `tracecontext`. `dd-opentracing-cpp`, on the other hand, will be deprecated once we remove it from all upstream projects (e.g. [ingress-nginx][2]).

Datadog's public documentation for C++ tracing has not yet been updated to recommend the newer [dd-trace-cpp][1], but I wholeheartedly recommend it.

How are you currently using `dd-opentracing-cpp`? Are you writing your own tracing code, or are you using it in conjunction with one of our supported proxies like nginx?

[1]: https://github.com/DataDog/dd-trace-cpp
[2]: https://github.com/kubernetes/ingress-nginx

**Comment by David-Wobrock** [comment]
Hey David 👋 

Thanks for your answer! I don't know how I missed [dd-trace-cpp](https://github.com/DataDog/dd-trace-cpp) 🤦 
We are using [dd-opentracing-cpp](https://github.com/DataDog/dd-opentracing-cpp/) with [nginx-opentracing](https://github.com/opentracing-contrib/nginx-opentracing) for an nginx.

I'll give a try to [nginx-datadog](https://github.com/DataDog/nginx-datadog), which I just discovered too 👀 , and keep you posted 🙂

**Comment by dgoffredo** [comment]
The most recent release of `nginx-datadog` still uses `dd-opentracing-cpp`. Recent changes upgrade it to use the newer `dd-trace-cpp` instead, but review is still pending on the documentation.

Your best bet is to wait a few days until `nginx-datadog` v1.0.0 is released, and then you can be the first to enjoy its `tracecontext` feature :)

I'll update this issue when the release is ready.

**Comment by dgoffredo** [comment]
@David-Wobrock 

I just published [nginx-datadog v1.0.0][1]. Check out its [readme][2] file, its [configuration documentation][3], and Datadog's [public documentation][4] (which mostly refers to the configuration documentation).

[1]: https://github.com/DataDog/nginx-datadog/releases/tag/v1.0.0
[2]: https://github.com/DataDog/nginx-datadog#readme
[3]: https://github.com/DataDog/nginx-datadog/blob/master/doc/API.md
[4]: https://docs.datadoghq.com/tracing/trace_collection/proxy_setup/?tab=nginx

**Comment by David-Wobrock** [comment]
Great! Thanks a lot!
That was quick 😄
