### ISSUE TITLE
Feature request: arm64 binaries

### ISSUE THREAD

**Issue by mcuelenaere** [DataDog/dd-opentracing-cpp#264]
https://github.com/opentracing-contrib/nginx-opentracing/issues/391 seems to have `linux/arm64` images, but AFAICS `dd-opentracing-cpp` does not provide arm64 builds. Is this on purpose or just an oversight? Would it be possible to provide arm64 binaries?

**Comment by dgoffredo** [comment]
`dd-opentracing-cpp` does not provide ARM64 binaries because the need has not yet arose, and because I do not have access to an ARM64 machine. Also, the CI system we use, CircleCI, does not support ARM64 beneath their docker executor (we'd have to switch to using VMs).

What's your use case? I can probably add this to our feature request pipeline. I see you opened a similar [issue in our nginx module repo][1].

[1]: https://github.com/DataDog/nginx-datadog/issues/31

**Comment by mcuelenaere** [comment]
Our usecase is that we are evaluating switching to AWS Graviton processors and atm this means we need to disable APM tracing for our nginx setup.

I see that https://circleci.com/docs/using-arm/ exists, but I'm not super familiar with CircleCI. Could QEMU work instead? I believe that's what Github Actions uses by default.

**Comment by dgoffredo** [comment]
Please submit this request as a support issue via <https://help.datadoghq.com/hc/en-us/requests/new> and reference these github issues. This way, the feature request is associated with your account and can be tracked internally.

> I see that https://circleci.com/docs/using-arm/ exists, but I'm not super familiar with CircleCI. Could QEMU work instead? I believe that's what Github Actions uses by default.

Our CI runs on CircleCI's built-in Docker executor. We could switch to using a "VM executor," but that might involve a rewrite of our CI configuration. Not a deal-breaker, but potentially time-consuming.

**Comment by mcuelenaere** [comment]
Issue filed!

**Comment by dgoffredo** [comment]
Thanks, let's leave this open, and I'll chase after whoever I need to internally.

**Comment by bwhaley** [comment]
Hi folks, any updates on this one? We'd also like to use Arm. Fwiw, CircleCI supports Arm for Docker executors now. See: https://circleci.com/docs/using-docker/#arm

**Comment by dgoffredo** [comment]
The non-OpenTracing version of the Datadog tracing nginx module, [nginx-datadog][1], has supported arm64 for a while. It's configured differently, but has feature parity. If you can afford to change all of your tracing configuration, migrating is an option.

[1]: https://github.com/datadog/nginx-datadog

**Comment by bwhaley** [comment]
Unfortunately that won't work in our case because it isn't compatible with openresty (https://github.com/DataDog/nginx-datadog/issues/30).

Any chance of adding Arm to the build process in this repo?

**Comment by dgoffredo** [comment]
Bummer. I'm no longer a maintainer of this repo, so I can't comment on its priority.

@dmehala for visibility.

**Comment by bwhaley** [comment]
Gotcha, well in that case, special thanks for your feedback anyway.

**Comment by dmehala** [comment]
Hi @bwhaley 

`dd-opentracing-cpp` is deprecated. There will be no further work on this library. Best outcome is to require OpenResty support [here](https://help.datadoghq.com/hc/en-us/requests/new?tf_1260824651490=pt_product_type:apm&tf_1260825272270=pt_apm_category_feature_request) for visibility.
