### ISSUE TITLE
Conflicting Datadog and B3 trace headers errors

### ISSUE THREAD

**Issue by qi-liao** [DataDog/dd-opentracing-cpp#274]
We recently enabled both Datadog and B3 style propagation tracing header in our service mesh, via setting the environment variable `"DD_PROPAGATION_STYLE_EXTRACT":"Datadog B3"`,

Then the Envoy proxies in our service mesh start throw lots of
`Attempt to deserialize SpanContext with conflicting Datadog and B3 headers` errors.  This exact error message can be tracked to  this repo's SpanContext::deserialize [[link]](https://github.com/DataDog/dd-opentracing-cpp/blob/master/src/span_context.cpp#L531):

```
  // It's also possible that a context is successfully extracted in two or more
  // different styles.  In that case, the resulting `SpanContext` objects must
  // all be equivalent (otherwise, which would we return?), where equivalence
  // is defined by `SpanContext::operator==`.
  for (PropagationStyle style : styles) {
    auto result = SpanContext::deserialize(logger, reader, propagation_headers[style]);
    if (!result) {
      return ot::make_unexpected(result.error());
    }
    if (result.value() != nullptr) {
      if (context != nullptr && *dynamic_cast<SpanContext *>(result.value().get()) !=
                                    *dynamic_cast<SpanContext *>(context.get())) {
        logger->Log(LogLevel::error,
                    "Attempt to deserialize SpanContext with conflicting Datadog and B3 headers");
        return ot::make_unexpected(ot::span_context_corrupted_error);
      }
```

Here are 2 example http request headers of ours that had this error raised against them:
```
{'x-datadog-trace-id': '8733085695601302500', 'x-datadog-parent-id': '7301421525389878719', 'x-datadog-sampling-priority': '-1', 
'x-b3-traceid': '00000000000000007932272b975c5be4', 'x-b3-spanid': '6553dc31584125bf', 'x-b3-sampled': '0' }

{'x-datadog-trace-id': '4331991475549422689', 'x-datadog-parent-id': '7928538397856214303', 'x-datadog-sampling-priority': '2', 
'x-b3-traceid': '00000000000000003c1e534b8e24c461', 'x-b3-spanid': '6e07d3aa6843ad1f', 'x-b3-sampled': '1' }
```
In both cases, trace_id and span_id headers for datadog and b3 have equivalent values (b3 in hex), the only difference between the 2 style of headers in the above examples is in the sampling header, where `'x-datadog-sampling-priority'` has a different value than the `'x-b3-sampled'` in both examples, -1 vs 0 or 2 vs 1, respectively.

However, `'x-datadog-sampling-priority'` has 4 valid values, -1, 0, 1, and 2, where 0 and -1 are different variations of do-not-sample, 1 and 2 are different variations of to-sample.  `'x-b3-sampled'` has only 2 valid values, 0 and 1 where 0 means do-not-sample and 1 means to-sample.

Is it possible that we could take into consideration the difference in valid values supported by `'x-datadog-sampling-priority'` and `'x-b3-sampled'` when doing the == check inside SpanContext::deserialize? The current behavior of raising deserialization error when there is just slight variation in sampling headers and returning empty pointer for parsed Span is causing trace IDs to get dropped at Envoy throughout our service mesh, breaking distributed tracing.

**Comment by dgoffredo** [comment]
Hi @qi-liao,

I agree with you. The "require them to be the same" logic ought to be less strict with regard to sampling priority.

In fact, the "require them to be the same" logic is removed in the [newer tracing library][1], which is available as of Envoy v1.26 or newer.

If you are able to upgrade the Envoys in your mesh, then the problem would likely go away. The new logic is "try the styles in order and stop when either extraction is successful or something is invalid." So, the Datadog context would be extracted, and that sampling priority would be used.

[1]: https://github.com/DataDog/dd-trace-cpp

**Comment by qi-liao** [comment]
Hi @dgoffredo 

Thank you for the response.

We are using istio. I just did a quick version check via
```

```

**Comment by qi-liao** [comment]
Thanks for this updated information. We will try upgrade istio to latest soon.

**Comment by qi-liao** [comment]
Want to close the loop and update here that after upgrading to Istio 1.19, these conflicting header errors have gone away for us. Thanks again, @dgoffredo!
