### ISSUE TITLE
error tag has been correct set, but the dashboard still show 0 errors

### ISSUE THREAD

**Issue by sanglt** [DataDog/dd-opentracing-cpp#74]
The `error` tag has been correct set (https://github.com/opentracing-contrib/nginx-opentracing/blob/master/opentracing/src/opentracing_context.cpp#L66) but in APM-UI its doesn't count 5xx as error.

This is the screen of service:
<img width="1507" alt="screen shot 2018-12-10 at 2 59 17 pm" src="https://user-images.githubusercontent.com/128535/49711689-8f06ab00-fc8c-11e8-8029-d78901a62b3f.png">
This is the detail of data for that trace:
<img width="646" alt="screen shot 2018-12-10 at 3 01 49 pm" src="https://user-images.githubusercontent.com/128535/49711713-a9408900-fc8c-11e8-8345-c23c35996404.png">

**Comment by wanx0007** [comment]
I open a pull request to fix both error and environment tag.
https://github.com/DataDog/dd-opentracing-cpp/pull/75
It's pending review.

**Comment by willgittoes-dd** [comment]
I made a new release so you could use the error feature ASAP.

https://github.com/DataDog/dd-opentracing-cpp/releases/tag/v0.3.8

**Comment by sanglt** [comment]
Thanks @willgittoes-dd,

I has testing version v3.0.8 and saw its still not working. The UI can saw the service, but the error trace has been removed, and the calc error rate is not affect too.

My test:
I created a fake service, which always return 503. I can saw the service register in dashboard, but with error rate is 0.
<img width="1512" alt="screen shot 2018-12-11 at 4 38 56 pm" src="https://user-images.githubusercontent.com/128535/49782801-5685d080-fd63-11e8-953a-df1558e0ebd7.png">

But when saw the service detail, its just have empty trace list:
<img width="1514" alt="screen shot 2018-12-11 at 4 40 13 pm" src="https://user-images.githubusercontent.com/128535/49782868-9c429900-fd63-11e8-936e-a184be06753a.png">

**Comment by willgittoes-dd** [comment]
Hi there, I do not have a problem creating an error using the error tag. Can you create a self-contained reproduction of your issue? 

<img width="1088" alt="screen shot 2018-12-12 at 12 10 01 pm" src="https://user-images.githubusercontent.com/36894588/49840323-09f3d100-fe07-11e8-8595-f94a80ea919b.png">

**Comment by sanglt** [comment]
Hi @willgittoes-dd

Thanks for quick response.

I has setup the demo repo here: https://github.com/sanglt/nginx-opentracing-dd-agent

Its still show empty error for me. I assume that the `error` tag is automatic set by nginx-opentracing (I can saw that tag correct when using v0.3.7): https://github.com/opentracing-contrib/nginx-opentracing/blob/master/opentracing/src/request_tracing.cpp#L68

<img width="1755" alt="screen shot 2018-12-12 at 12 54 35 pm" src="https://user-images.githubusercontent.com/128535/49844218-bfc21e00-fe0d-11e8-9d7f-acd1ef70d80d.png">

P/S:
Also I got a very critical issue with v0.3.8, that is any 5xx response will made the nginx worker exit. This increase the error of our backend and I has change to use v0.3.7 for now.
You can saw from the log from my repo:
```nginx_1     | terminate called without an active exception
nginx_1     | 2018/12/12 02:49:50 [alert] 1#1: worker process 23 exited on signal 6
```
Usually nginx will spin new worker for this. But if the container is handle many traffic, we will got the 'empty response` since no worker is available.

Thanks,

**Comment by wanx0007** [comment]
Ops, my bad on using stoi() on the tag value.  I don't use the nginx tracing module, so I was not aware of the correct usage (boolean) when I submitted the PR.  Since SpanData.error is int32_t, I assume that it's passed in as an integer.
