### ISSUE TITLE
How can I enable distributed tracing?

### ISSUE THREAD

**Issue by keattang** [DataDog/dd-opentracing-cpp#97]
Hi, 

I have nginx sitting in front of my python web server. Both are instrumented with dd-trace but the traces from nginx are not linked to my traces in python. They are linked when the request comes from another service that sends them but not when they come from the wider internet.

How can I get the nginx tracer to add the required distributed tracing headers to make this happen?

**Comment by cgilmour** [comment]
Can you share the nginx config?
The docs here explain the changes required to enable the tracing: https://docs.datadoghq.com/tracing/setup/nginx/#nginx-configuration

> They are linked when the request comes from another service that sends them but not when they come from the wider internet.

Does this request go through nginx, or directly to the python web server?

**Comment by keattang** [comment]
All requests go through nginx. The python web server works on a socket file and so can't accept outside requests.

This is a simplified version of my `nginx.conf`. The trace parts are taken directly from the docs:
```
load_module modules/ngx_http_opentracing_module.so; # Load OpenTracing module


http {
  upstream web-server {
    # for UNIX domain socket setups
    server unix:/dev/shm/gunicorn.sock fail_timeout=0;
  }

  opentracing on; # Enable OpenTracing
  opentracing_tag http_user_agent $http_user_agent; # Add a tag to each trace!
  opentracing_trace_locations off; # Emit only one span per request.

  # Load the Datadog tracing implementation, and the given config file.
  opentracing_load_tracer /usr/local/lib/libdd_opentracing_plugin.so /etc/dd-config.json;

  server {
    listen 5000 deferred;

    location / {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
      proxy_set_header Host $http_host;

      # Set the per request tracing tags
      opentracing_operation_name "$request_method $uri";
      opentracing_tag "resource.name" "/";
      opentracing_tag "http.query_params" $args;

      proxy_pass http://web-server;
    }
  }
}
```

**Comment by keattang** [comment]
My `dd-config.json` looks like this:
```
{
  "service": "web-server-nginx",
  "agent_host": "$DATADOG_TRACE_AGENT_HOSTNAME",
  "environment": "$ENV",
  "operation_name_override": "nginx.handle"
}
```

**Comment by cgilmour** [comment]
Thanks for providing those details. I'll try to reproduce the problem you've described with those configs.

**Comment by keattang** [comment]
Awesome thanks!

**Comment by cgilmour** [comment]
Can you try adding `opentracing_propagate_context;` to your `location` block? Eg:
```
      # Set the per request tracing tags
      opentracing_operation_name "$request_method $uri";
      opentracing_tag "resource.name" "/";
      opentracing_tag "http.query_params" $args;
      opentracing_propagate_context;
```

**Comment by keattang** [comment]
That did the trick! Thanks for the help!

**Comment by cgilmour** [comment]
That’s good news. I’ll update the docs.
